### ISSUE TITLE
Instructions for Adding the Data connection secret

### ISSUE THREAD

**Issue by strangiato** [adrien-legros/rhods-mnist#2]
In the lab instructions for [Edit the Data connection secret](https://github.com/strangiato/rhods-mnist-demo/blob/main/docs/lab-instructions.md#edit-the-data-connections-secret), users are instructed to `add the S3 credentials to the notebook` and the screenshot shows the page to edit the data connection, implying that the user needs to enter this information.

This secret has already been created [here](https://github.com/adrien-legros/rhods-mnist/blob/main/openshift-data-science/data-science-project/s3-connection-secret.yaml) however and the user should instead be instructed to `Add an existing connection`.

**Comment by adrien-legros** [comment]
Thanks ! I changed the lab instructions as it is now possible to directly choose a data connection from the workbench creation page.
