### ISSUE TITLE
Missing instructions for uploading data

### ISSUE THREAD

**Issue by strangiato** [adrien-legros/rhods-mnist#4]
In the `Pre-processing.ipynb` file section 2.1 includes instructions to download data from S3:

```
s3_client.download_file(bucket_name, "data/train.csv", '/tmp/train.csv')
s3_client.download_file(bucket_name, "data/test.csv", '/tmp/test.csv')
```

There are currently no instructions to create those data sources in the S3 bucket in the lab setup however so the pre-processing steps fail.

**Comment by adrien-legros** [comment]
Thanks again !
You are right, I was running the lab/reset/job.yaml as an initialization but I didn't explained it anywhere.
In a54b9184e58dfea9e0f15569b9f509f78e827dd8 I created a initialization job that pulls the dataset into rhods minio bucket. I tested it manually. Please reopen if I missed something :)
